version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: gruzy_ryadom
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  app:
    build: ./backend
    environment:
      DRIVER_BOT_TOKEN: ${DRIVER_BOT_TOKEN}
      ADMIN_BOT_TOKEN: ${ADMIN_BOT_TOKEN}
    volumes:
      - ./config.yaml:/app/config.yaml
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  postgres_data:
